<a href="https://colab.research.google.com/github/abhishek-383/Data-science---45-days/blob/main/Day14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Coloum add & rename**

In [ ]:
import pandas as pd
d = {
    "name":["vishal","virat","vineet"], # 3 rows
    "salary":[100,200,300] # 3 rows
}
df = pd.DataFrame(data=d)
# add single column
df["marks"] = [10,20,30]
df["marks"] = df["salary"] / 2
df["increment"] = df["salary"] + (df["salary"] / 10)
# column name change
df.rename(columns={"increment":"salary_increment"},inplace=True)
df.drop(["salary","name"],axis=1,inplace=True)
df

[[1. 0.]
 [0. 1.]]

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/file2.json"
df  = pd.read_json(url)
# single column ka data get krne k liye
df["name"]
# add single column

df["salary"] = df["marks"] + 100
# add single column
df["salary12"] = [100,200,300,400,500]
df

       name  roll no  marks  salary  salary12
0   dheeraj      123     10     110       100
1     kunal     1234     20     120       200
2  abhishek    12345     30     130       300
3   praveen    12356     40     140       400
4    anjali  1234567     50     150       500

In [ ]:
# to get data
print(df.loc[3,"roll no"])
print(df.iloc[2,1]) # specific element
print(df.iloc[0])
print(df.loc[0])

print(df.iloc[0:3])
print(df.loc[0:2])
subdata_set = df.loc[0:3,["name", "roll no", "marks"]]
subdata_set
subdata_set = df.iloc[0:3,[0,1,2,3]]
subdata_set

12356
12345
name        dheeraj
roll no         123
marks            10
salary          110
salary12        100
Name: 0, dtype: object
name        dheeraj
roll no         123
marks            10
salary          110
salary12        100
Name: 0, dtype: object
       name  roll no  marks  salary  salary12
0   dheeraj      123     10     110       100
1     kunal     1234     20     120       200
2  abhishek    12345     30     130       300
       name  roll no  marks  salary  salary12
0   dheeraj      123     10     110       100
1     kunal     1234     20     120       200
2  abhishek    12345     30     130       300

       name  roll no  marks  salary
0   dheeraj      123     10     110
1     kunal     1234     20     120
2  abhishek    12345     30     130

In [ ]:
data = {
"Emp_ID": [101, 102, 103, 104, 105, 106],
"Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
"Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
"Salary": [50000, 45000, 60000, 55000, 48000, 52000],
"Experience": [2, 3, 5, 4, 1, 3]

}
import pandas as pd
df = pd.DataFrame(data)
print(df)
df["age"] = [18,20,41,23,22,33]
df.drop(["Salary","Name"],axis=1,inplace=True)
df
print(df.loc[0:3])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID Department  Experience  age
0     101         IT           2   18
1     102         HR           3   20
2     103    Finance           5   41
3     104         IT           4   23

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/student-data1.json"
df  = pd.read_json(url)
print(df)
print(df.iloc[0:6,[0,1]])
print(df.loc[1:5,"name"])
print(df.iloc[[3,8],[0]])
print(df.iloc[3:9:5,0])
# filter

df[df["english"] == 95]

df[df["maths"] > 60]

#multiple conditions
print(df[(df["english"] > 60) & (df["maths"] > 60)]["name"])
print(df[(df["english"] > 60) | (df["maths"] > 60)]["name"])

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
      name  gender
0     arun    Male
1   rajesh    Male
2  moorthy    Male
3     raja    Male
4     usha  Female
5    priya  Female
1     rajesh
2    moorthy
3       raja
4       usha
5      priya
Name: name, dtype: object
     name
3    raja
8  Dinesh
3      raja
8    Dinesh
Name: name, dtype: object
0        arun
1      rajesh
2     moorthy
6      Sundar
7     Kavitha
10      Gowri
12    Murugan
13    Jenifer
Name: name, dtype: object
0        arun
1      rajesh
2     moorthy
4        usha
5       priya
6      Sundar
7     Kavitha
8      Dinesh
9        Hema
10      Gowri
12    Murugan
13    Jenifer
Name: name, dtype: object