<a href="https://colab.research.google.com/github/abhishek-383/Data-science---45-days/blob/main/Day15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Sorting**
1. df.sort_values("column_name") -> Sort by Single Column
2. df.sort_values("Age", ascending=True) -> Sort in Ascending Order
3. df.sort_values("Age", ascending=False) -> Sort in Descending Order
4. df.sort_values(["col1", "col2"]) -> Sort Multiple Columns
5. df.sort_values( ["Age", "Salary"], ascending=[True, False] ) -> Multiple Columns with Descending Order

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/PraveenBunker/45-days-of-python/main/student-data1.json"
df  = pd.read_json(url)
df.sort_values("english")    #  by default ascending
df.sort_values("name",ascending=[False])  # descending

df.sort_values(by=["english"],ascending=False)
df.sort_values(by=["english","maths"],ascending=[False,True])

df["name"] = df["name"].str.lower()
print(df.sort_values(by=["name"],ascending=[True]))

       name  gender  physics  maths  english
0      arun    Male       88     87       78
8    dinesh    Male       56     45       67
10    gowri  Female      100    100      100
9      hema  Female       71     90       23
13  jenifer  Female       67     88       90
7   kavitha  Female       78     71       67
2   moorthy    Male       89     90       70
12  murugan    Male       34     89       78
5     priya  Female       56     46       78
3      raja    Male       30     25       40
1    rajesh    Male       96    100       95
11      ram    Male       78     55       47
6    sundar    Male       12     67       67
4      usha  Female       67     45       78

# **Operations on rows and** **columns**
1. Add
2. Update
3. Delete

In [ ]:
#
df
# Add coloum
df["Total"] = df["physics"]+df["maths"]+df["english"]
df
# Add row
df.loc[14] = ["abhi","male","92","99","88","279"]
df
# update coloum
df["Total"] = df["physics"]+df["maths"]+df["english"]
df

# update row
df.loc[14] = ["abhi","male","92","99","88","279"]
df

# delete coloum
df.drop("Total",axis=1)

# delete row
df.drop(14,axis=0)

       name  gender physics maths english Total
0      arun    Male      88    87      78   253
1    rajesh    Male      96   100      95   291
2   moorthy    Male      89    90      70   249
3      raja    Male      30    25      40    95
4      usha  Female      67    45      78   190
5     priya  Female      56    46      78   180
6    sundar    Male      12    67      67   146
7   kavitha  Female      78    71      67   216
8    dinesh    Male      56    45      67   168
9      hema  Female      71    90      23   184
10    gowri  Female     100   100     100   300
11      ram    Male      78    55      47   180
12  murugan    Male      34    89      78   201
13  jenifer  Female      67    88      90   245
14     abhi    male      92    99      88   279

### **Working with date** **value**
1. df['doj'] -> Add New Date Column
2. df['doj'].dtype -> Check Data Type of Date Column
3. df['doj'] = pd.to_datetime(df['doj']) -> Convert Object to Datetime
4. df['doj'].dtype -> Check Data Type of Date Column
5. pd.Timestamp.now() -> Get Current Date & Time
6. df['doj'].dt.year -> Extract Year
7. df['doj'].dt.month -> Extract Month
8. df['doj'].dt.day -> Extract Day
9. df[(df['doj'] >= '2024-01-01') & (df['doj'] <= '2024-12-31')] -> Filter Between Two Dates

In [ ]:

import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df['doj'] = ['2025-01-01',"2025-02-02","2025-03-03","2025-04-04","2025-05-05"]
df
df['doj'].dtype   # output ('O') it means string type
df['doj'] = pd.to_datetime(df['doj'])
df['doj'].dtype # output ('<M8[ns]') it means date formate

# Date operation
df['doj'].dt.year
df['doj'].dt.month
df['doj'].dt.day
df['doj'].dt.day_name()
df['doj'].dt.is_leap_year

#add 20 days
# df['doj'] + pd.Timedelta(days=20)
df['doj'] + pd.to_timedelta("20 days")

0   2025-01-21
1   2025-02-22
2   2025-03-23
3   2025-04-24
4   2025-05-25
Name: doj, dtype: datetime64[ns]